default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: questionit_development
  username: username
  password: password

test:
  <<: *default
  database: questionit_test
  username: username
  password: password